# Travis
---
# language: not python
addons:
  apt:
    packages:
    # - elinks # Needs pygmentize -f html -O full

before_install:
- ls --color -a
- ls --color -a ~
- ls --color ~/virtualenv
- ls --color ~/virtualenv/python2.7
- ls --color ~/virtualenv/python2.7/bin
- which python
- python --version

- which pip
- which pip2
- which pip2.7
- pip --help
- pip --version
- pip install --upgrade pip # Upgrading pip
- pip --version

- which virtualenv
- virtualenv --version
- pip install --upgrade virtualenv # Upgrading virtualenv
- virtualenv --version

install:
- pip install --user --verbose --verbose --verbose pygments
# --user is required for language: <not> python to use python 2 (python 3 seems unsupported)

before_script:
- which pygmentize

script:
- true
