# Travis
---
# language: not python
addons:
  apt:
    packages:
    # - elinks # Needs pygmentize -f html -O full

before_install:
- ls --color -a
- ls --color -a ~
- ls --color ~/virtualenv
- ls --color ~/virtualenv/python2.7
- ls --color ~/virtualenv/python2.7/bin

- command -v pyenv
- pyenv --help
- pyenv versions
- pyenv version
- pushd ~
- pyenv version
- popd

- command -v python
- python --version

- command -v pip
- command -v pip2
- command -v pip2.7
- pip --help
- pip --version

- command -v virtualenv
- virtualenv --version
- pip install --upgrade virtualenv # Upgrading virtualenv
- virtualenv --version

install:
- pip install --user --verbose --verbose --verbose pygments
# --user is required for language: <not> python to use python 2 (python 3 seems unsupported)

before_script:
- command -v pygmentize

script:
- true

after_script:
- pip install --upgrade pip # Upgrading pip
- pip --version
